{
 "title": "Flow loss counters",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic Loss percentage",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(flow) (byteblower_gui_traffic_bytes_total{direction=\"tx\"}) - sum by (flow) (byteblower_gui_traffic_bytes_total{direction=\"rx\"})) / sum by(flow) (byteblower_gui_traffic_bytes_total{direction=\"tx\"})"
    }
   ]
  },
  {
   "title": "Total traffic lost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(byteblower_gui_traffic_bytes_total{direction=\"tx\"}) -  sum(byteblower_gui_traffic_bytes_total{direction=\"rx\"})"
    }
   ]
  },
  {
   "title": "Lost traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(flow) (byteblower_gui_traffic_bytes_total{direction=\"tx\"}) - sum by (flow) (byteblower_gui_traffic_bytes_total{direction=\"rx\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}