{
 "title": "Flow throughput",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(byteblower_gui_traffic_bytes_total{direction=\"rx\"}[30s])) * 8",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "Current rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(byteblower_gui_traffic_bytes_total{direction=\"rx\"}[30s])) *8"
    }
   ]
  },
  {
   "title": "Flow throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(byteblower_gui_traffic_bytes_total{direction=\"rx\"}[30s]) * 8",
     "legendFormat": "{{flow}} @  {{instance}}"
    }
   ]
  }
 ]
}