{
 "title": "byteblower_usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "System usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time((group(byteblower_gui_traffic_bytes_created) or vector(0))[$__interval:])"
    }
   ]
  },
  {
   "title": "ByteBlower Ports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(port) (resets(byteblower_gui_traffic_bytes_total[20s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byteblower Flows",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(flow) (resets(byteblower_gui_traffic_bytes_created[30s])))",
     "legendFormat": "Port"
    }
   ]
  },
  {
   "title": "Tx Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(byteblower_gui_traffic_bytes_total{direction=\"tx\"}[1m])) * 8"
    }
   ]
  },
  {
   "title": "Rx Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(byteblower_gui_traffic_bytes_total{direction=\"rx\"}[1m])) * 8"
    }
   ]
  }
 ]
}