{
 "title": "tabular_overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Flow names",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by(flow) (byteblower_gui_traffic_bytes_created)"
    }
   ]
  },
  {
   "title": "ByteBlower ports",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "group by(port,direction) (byteblower_gui_traffic_bytes_created)"
    }
   ]
  },
  {
   "title": "ByteBlower GUIs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by(instance) (byteblower_gui_traffic_bytes_created)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency flows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "byteblower_gui_latency_average_seconds"
    }
   ]
  }
 ]
}